function checkForm(){
	if(document.getElementById('formtypeselect').value!='marriage')
	{
		document.getElementById('birthpname').value='';
		document.getElementById('birthpname').disabled=false;
		document.getElementById('birthdoe').value='';
		document.getElementById('birthdoe').disabled=false;
		document.getElementById('birthfname').value='';
		document.getElementById('birthfname').disabled=false;
		document.getElementById('birthmname').value='';
		document.getElementById('birthmname').disabled=false;
		document.getElementById('birthpadd').value='';
		document.getElementById('birthpadd').disabled=false;
	}
	else
	{
		document.getElementById('birthpname').value='NA';
		document.getElementById('birthpname').disabled=true;
		document.getElementById('birthdoe').value='NA';
		document.getElementById('birthdoe').disabled=true;
		document.getElementById('birthfname').value='NA';
		document.getElementById('birthfname').disabled=true;
		document.getElementById('birthmname').value='NA';
		document.getElementById('birthmname').disabled=true;
		document.getElementById('birthpadd').value='NA';
		document.getElementById('birthpadd').disabled=true;
	}	
}